[package]
name = "draw"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
bytemuck = { version = "1.25", features = ["derive"] }
image = { version = "0.25", default-features = false, features = ["gif", "jpeg", "png"] }
parley.workspace = true
roxmltree = "0.21"
swash = "0.2.10"
wgpu.workspace = true

[dev-dependencies]
pollster = "0.4"
png = "0.18"
