Composition {
	CurrentTime = 0,
	RenderRange = { 0, 0 },
	GlobalRange = { 0, 1 },
	CurrentID = 72,
	HiQ = true,
	PlaybackUpdateMode = 0,
	StereoMode = false,
	Version = "Fusion Studio 20.3.1 build 5",
	SavedOutputs = 0,
	HeldTools = 0,
	DisabledTools = 0,
	LockedTools = 0,
	AudioOffset = 0,
	Resumable = true,
	OutputClips = {
		"Comp:/../Snowbound-Sequoia0000.png",
		"Comp:/../Snowbound-SnowLeopard0000.png"
	},
	Tools = {
		Notebook_2010 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "Comp:/../renders/SnowLeopard.png",
					FormatID = "PNGFormat",
					StartFrame = -1,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 0,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 0,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 0
				}
			},
			CtrlWZoom = false,
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				["Clip1.PNGFormat.PostMultiply"] = Input { Value = 1, }
			},
			ViewInfo = OperatorInfo { Pos = { 55, 82.197 } },
		},
		Notebook_15 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "Comp:/../renders/Sequoia.png",
					FormatID = "PNGFormat",
					StartFrame = -1,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 0,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 0,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 0
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				["Clip1.PNGFormat.PostMultiply"] = Input { Value = 1, }
			},
			ViewInfo = OperatorInfo { Pos = { 55, 148.197 } },
		},
		Dock_shadow_2010 = Shadow {
			Inputs = {
				ShadowOffset = Input { Value = { 0.503, 0.494 }, },
				Softness = Input { Value = 0.012, },
				Alpha = Input { Value = 0.25, },
				Input = Input {
					SourceOp = "Finish_2010",
					Source = "Output",
				}
			},
			ViewInfo = OperatorInfo { Pos = { 495, 82.197 } },
		},
		Export_15 = Saver {
			CtrlWZoom = false,
			Inputs = {
				["OpenEXRFormat.ZipCompressionLevel"] = Input {
					Value = Number {
						Value = 4
					},
				},
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "Comp:/../Snowbound-Sequoia0000.png",
						FormatID = "PNGFormat",
						Saving = true,
						LengthSetManually = true,
						TrimIn = 0,
						TrimOut = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = 0,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Dock_shadow_15",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, }
			},
			ViewInfo = OperatorInfo { Pos = { 715, 148.197 } },
		},
		Finish_2010 = ColorCorrector {
			CtrlWZoom = false,
			Inputs = {
				ColorRanges = Input {
					Value = ColorCurves {
						Curves = {
							{
								Points = {
									{ 0, 1 },
									{ 0.4, 0.2 },
									{ 0.6, 0 },
									{ 1, 0 }
								}
							},
							{
								Points = {
									{ 0, 0 },
									{ 0.4, 0 },
									{ 0.6, 0.2 },
									{ 1, 1 }
								}
							}
						}
					},
				},
				PreDividePostMultiply = Input { Value = 1, },
				HistogramIgnoreTransparent = Input { Value = 1, },
				Input = Input {
					SourceOp = "Notebook_2010",
					Source = "Output",
				}
			},
			ViewInfo = OperatorInfo { Pos = { 275, 82.197 } },
		},
		Finish_15 = ColorCorrector {
			CtrlWZoom = false,
			Inputs = {
				ColorRanges = Input {
					Value = ColorCurves {
						Curves = {
							{
								Points = {
									{ 0, 1 },
									{ 0.4, 0.2 },
									{ 0.6, 0 },
									{ 1, 0 }
								}
							},
							{
								Points = {
									{ 0, 0 },
									{ 0.4, 0 },
									{ 0.6, 0.2 },
									{ 1, 1 }
								}
							}
						}
					},
				},
				PreDividePostMultiply = Input { Value = 1, },
				HistogramIgnoreTransparent = Input { Value = 1, },
				Input = Input {
					SourceOp = "Notebook_15",
					Source = "Output",
				}
			},
			ViewInfo = OperatorInfo { Pos = { 275, 148.197 } },
		},
		Export_2010 = Saver {
			Inputs = {
				["OpenEXRFormat.ZipCompressionLevel"] = Input {
					Value = Number {
						Value = 4
					},
				},
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "Comp:/../Snowbound-SnowLeopard0000.png",
						FormatID = "PNGFormat",
						Saving = true,
						LengthSetManually = true,
						TrimIn = 0,
						TrimOut = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = 0,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Dock_shadow_2010",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, }
			},
			ViewInfo = OperatorInfo { Pos = { 715, 82.197 } },
		},
		Dock_shadow_15 = Shadow {
			Inputs = {
				ShadowOffset = Input { Value = { 0.503, 0.494 }, },
				Softness = Input { Value = 0.012, },
				Alpha = Input { Value = 0.25, },
				Input = Input {
					SourceOp = "Finish_15",
					Source = "Output",
				}
			},
			ViewInfo = OperatorInfo { Pos = { 495, 148.197 } },
		}
	},
	Frames = {
		{
			FrameTypeID = "ChildFrame",
			Mode = 3,
			LayoutPreset = 0,
			PresetName = "Default",
			Left = 0,
			Top = 27,
			Width = 1280,
			Height = 644,
			ZoneInfo = {
				AuxRight = { Expanded = true },
				["!Left"] = {
				},
				AuxLeft = { Expanded = true },
				Right = { Expanded = true, },
				Left = { Expanded = false, },
				["!Right"] = {
				}
			},
			ViewInfo = {
				Viewer1 = { Show = true, RatioY = 0.01, RatioX = 1, },
				InnerLeft = {
				},
				MainSplit = {
					RatioX = 100,
					RatioY = 0.998344370860927,
				},
				CenterSplit = {
					RatioX = 1,
					RatioY = 100,
				},
				Viewer2 = { Show = true, RatioY = 0.01, RatioX = 1, },
				Comments = { Show = false },
				Time = { Show = true, RatioX = 100, },
				InnerColumns = {
					RatioX = 100,
					RatioY = 2.00165562913907,
				},
				Keyframes = { Show = true, Adjust = false, RatioY = 100, MRU = 2, RatioX = 0.999999999999999, },
				LayoutStrip = { Show = true, RatioX = 100, },
				Inspector = { Show = true, RatioY = 1, RatioX = 100, },
				InnerRight = {
				},
				MediaPool = { Show = false, },
				OuterColumns = {
					RatioX = 100,
					RatioY = 1,
				},
				Effects = { Show = false, },
				ActionStrip = { Show = false, Adjust = true, MRU = 0, RatioX = 100, },
				Metadata = { Show = false, },
				OuterLeft = {
				},
				ViewerSplit = {
					RatioX = 100,
					RatioY = 1,
				},
				Nodes = { Show = true, RatioY = 100, RatioX = 0.999999999999999, },
				OuterRight = {
					PixelX = 420,
					RatioY = 100,
				},
				Clips = { Show = false, },
				Spline = { Show = true, Adjust = false, RatioY = 100, MRU = 1, RatioX = 0.999999999999999, }
			},
			Views = ordered() {
				Effects = MultiView {
					Active = "EffectView",
					ViewList = ordered() {
						EffectView = "EffectView"
					},
				},
				Nodes = MultiView {
					Active = "FlowView",
					ViewList = ordered() {
						FlowView = "FlowView"
					},
					FlowView = FlowView {
						Flags = {
							Navigator = true,
							AutoHideNavigator = true,
							AutoSnap = true,
							RemoveRouters = true
						},
						NavigatorSize = { 200, 140 },
						Direction = "Horizontal",
						PipeStyle = "Direct",
						RootScale = 1,
						RootOffset = { 130, 29 }
					}
				},
				Keyframes = MultiView {
					Active = "TimelineView",
					ViewList = ordered() {
						TimelineView = "TimelineView"
					},
					TimelineView = TimelineView {
						TreeControlState = {
						},
						DisplayMode = "All Tools",
						ShowCurrentTimeTools = false,
						Filter = "Show All",
						ShowSelectedTools = false,
						ShowAnimatedToolsOnly = false,
						ShowEditBoxes = false,
						KeyFrameView = {
							Position = { Left = 232, Bottom = 139 },
							ScaleX = 2.28215767634855,
							OffsetX = -11.4107883817427,
							OffsetY = 0,
							AutoScaling = "scroll",
							AutoSnapTo = "frame",
							AutoSnapToGuidelines = true,
							GuidelinesGrabEnabled = true,
							GuidelinesSnapTo = "none"
						},
						Spreadsheet = { LeftPos = 232, Visible = false }
					}
				},
				Spline = MultiView {
					Active = "SplineView",
					ViewList = ordered() {
						SplineView = "SplineEditorView"
					},
					SplineView = SplineEditorView {
						LeftPos = 264,
						ScaleX = 0.2,
						ScaleY = 0.00338983050847458,
						OffsetX = -0.2,
						OffsetY = 0,
						AutoScaling = "scroll",
						AutoSnapTo = "frame",
						AutoSnapToGuidelines = true,
						GuidelinesSnapTo = "frame",
						ShowKeyMarkers = false,
						IndependentHandles = false,
						ShowNonSplineModifiers = false,
						GuidelinesGrabEnabled = true,
						ShowOneToolOnly = false,
						ShowSelectedTools = false,
						ShowAllInputs = false,
						Filter = "Show All"
					}
				},
				Inspector = MultiView {
					Active = "Tools",
					ViewList = ordered() {
						Tools = "ControlView",
						Modifiers = "ModifierView"
					},
				},
				Viewer1 = MultiView {
					Active = "LeftView",
					ViewList = ordered() {
						LeftView = "PreviewContainer"
					},
				},
				Viewer2 = MultiView {
					Active = "RightView",
					ViewList = ordered() {
						RightView = "PreviewContainer"
					},
				},
				Time = "TimeView",
				ActionStrip = "ActionStripView",
				LayoutStrip = "LayoutStripView"
			},
			Layout = {
				{ ID = "LayoutStrip", FixedY = 36, Resolve = false, Flat = true },
				{
					{
						{ ID = "MediaPool", Fusion = false, RatioX = 1 },
						{ ID = "Effects", RatioX = 1 },
						Zone = "Left",
						Rows = 2,
						PaneID = "OuterLeft",
						PixelX = 420
					},
					{
						{
							{
								{ ID = "MediaPool", Fusion = false, RatioX = 1 },
								{ ID = "Effects", RatioX = 1 },
								PaneID = "InnerLeft",
								MaxViews = 1,
								PixelX = 420,
								Rows = 2,
								Zone = "!Left"
							},
							{
								{
									{ ID = "Viewer1", RatioY = 0.01, RatioX = 1 },
									{ ID = "Viewer2", RatioX = 1 },
									RatioY = 1,
									Columns = 2,
									PaneID = "ViewerSplit"
								},
								{ ID = "Time", FixedY = 83, Flat = true },
								RatioX = 1,
								Rows = 2
							},
							{
								{ ID = "Inspector", RatioY = 1 },
								{ ID = "Metadata", RatioY = 1, Fusion = false },
								PaneID = "InnerRight",
								MaxViews = 1,
								PixelX = 420,
								Rows = 2,
								Zone = "!Right"
							},
							RatioY = 2,
							Columns = 3,
							PaneID = "InnerColumns"
						},
						{ ID = "ActionStrip", FixedY = 50, Flat = true },
						{
							{ ID = "Nodes", RatioX = 1 },
							{ ID = "Spline", RatioX = 1 },
							{ ID = "Keyframes", RatioX = 1 },
							RatioY = 1,
							Columns = 3,
							PaneID = "MainSplit"
						},
						{ Fusion = false, ID = "Clips", LARGE_FixedY = 160, MEDIUM_FixedY = 138, SMALL_FixedY = 110 },
						RatioX = 1,
						Rows = 4,
						PaneID = "CenterSplit"
					},
					{
						{ ID = "Inspector", RatioY = 1 },
						{ ID = "Metadata", RatioY = 1, Fusion = false },
						Zone = "Right",
						Rows = 2,
						PaneID = "OuterRight",
						PixelX = 420
					},
					RatioY = 1,
					Columns = 3,
					PaneID = "OuterColumns"
				},
				RatioX = 1,
				Rows = 2,
				RatioY = 1
			},
			TopBar = {
				Left = { "Left", "MediaPool", "Effects", "Clips", "Nodes", "Console" },
				Right = { "Spline", "Keyframes", "Metadata", "Inspector", "Right" }
			}
		}
	},
	Prefs = {
		Comp = {
			AutoSave = {
				Delay = 60,
			},
			Memory = {
				FramesAtOnce = 4,
				Interactive = {
					SimultaneousBranching = true,
				}
			},
			Views = {
				RightView = {
					Viewer = {
						Layer = ":Default"
					},
				},
				LeftView = {
					Viewer = {
						Layer = ":Default"
					},
				},
				View1 = {
					PickH = 1,
					PickW = 1,
					AlwaysOnTop = true,
					FullScreen = false,
				},
				Defaults = {
					View3D = {
						Options = {
							ShowUVTangentVectors = false
						},
						TextureDepth = "int8"
					},
					Guides = {
						SafeTitle = true,
						SafeImage = true,
						Center = true,
					},
					MaterialViewer = {
						Options = {
							TextureDepth = "int8"
						},
					},
				},
				["Image View"] = {
					Viewer = {
						ScaleMode = 1
					}
				}
			},
			Preview = {
				SkipFrames = true,
				ActiveLoaders = false,
				ActiveSavers = false,
			},
			Paths = {
				Map = {
					["ResolveCaches:"] = "Temp:DiskCache",
				},
			},
			FrameFormat = {
				Width = 1024,
				Height = 1024,
				GuideRatio = 1.77777777777778,
			},
			Unsorted = {
				GlobalEnd = 1,
				RenderSettings = {
					Configs = {
						Preview = {
							StepRender = false,
							PriorityClasses = "all",
							ShowRenderNodes = false,
							SizeType = 1,
							CustomAspect = true,
							CustomHeight = 160,
							StepSize = 5,
							CustomWidth = 200,
							MotionBlur = true,
							UpdateMode = "Some",
							UseNetwork = false,
							Quality = true
						},
						Final = {
							StepRender = false,
							PriorityClasses = "all",
							ShowRenderNodes = false,
							SizeType = 1,
							CustomAspect = true,
							CustomHeight = 160,
							StepSize = 5,
							CustomWidth = 200,
							MotionBlur = true,
							UpdateMode = "Some",
							UseNetwork = false,
							Quality = true
						}
					},
					PreviewConfig = "Preview",
					CurrentConfig = "Final"
				}
			},
			Tweaks = {
				OpenCL = {
					Enable = 2,
					Caching = 2
				}
			},
			LUTView = {
				ShowTips = true,
			},
			Cluster = {
				SlaveClasses = "all"
			},
			FlowView = {
				FullToolIndicator = false
			},
			QuickTime = {
			},
		}
	},
}
