[package]
name = "onestore-notebook"
version = "0.1.0"
edition = "2024"
publish = false

[features]
smb = ["dep:onestore-smb"]
protected = ["onestore/protected", "dep:zeroize"]

[dependencies]
onestore = { path = "../onestore" }
onestore-smb = { path = "../onestore-smb", optional = true }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
zeroize = { version = "1.9.0", optional = true }

[dev-dependencies]
serde_json = "1"
tempfile = "3"
