[package]
name = "one-canvas-gpu"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
onestore = { path = "../onestore" }
one-canvas = { path = "../canvas" }
bytemuck = { version = "1.25", features = ["derive"] }
swash = "0.2.10"
parley.workspace = true
wgpu.workspace = true
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }

[dev-dependencies]
pollster = "0.4"
png = "0.18"
